export default [
	{
		name: 'Инсульт',
		percent: 32,
		image: 'pic/brain.png',
		value1: 'I23',
		value2: 'I32-I98',
		isActive: true,
	},
	{
		name: 'Инфаркт',
		percent: 27,
		value1: 'A73',
		value2: 'A12-A48',
		image: 'pic/heart.png',
		isActive: true,
	},
	{
		name: 'Сахарный диабет',
		percent: 14,
		value1: 'Q99',
		value2: 'Q98-Q48',
		image: 'pic/candy.png',
		isActive: false,
	},
	{
		name: 'Болезнь альцгеймера',
		percent: 32,
		value1: 'P11',
		value2: 'P19-P50',
		image: 'pic/brain1.png',
		isActive: true,
	},
	{
		name: 'Язва желудка',
		percent: 20,
		value1: 'K25',
		value2: 'K00-K93',
		image: 'pic/yazva_jeludka.svg',
		isActive: true,
	},
	{
		name: 'Анемия жел-я',
		percent: 20,
		value1: 'D50',
		value2: 'D50-D89',
		image: 'pic/anemia_jel-za.svg',
		isActive: false,
	},
	{
		name: 'Тиреотоксикоз',
		percent: 20,
		value1: 'E05',
		value2: 'E00-K90',
		image: 'pic/tereotoksikoz.svg',
		isActive: true,
	},
	{
		name: 'Мигрень',
		percent: 20,
		value1: 'G43',
		value2: 'G00-G99',
		image: 'pic/migren.svg',
		isActive: false,
	},
	{
		name: 'Глаукома',
		percent: 20,
		value1: 'H40',
		value2: 'H00-H59',
		image: 'pic/glaukoma.svg',
		isActive: false,
	},
	{
		name: 'Отосклероз',
		percent: 20,
		value1: 'H80',
		value2: 'H60-H95',
		image: 'pic/otoskleroz.svg',
		isActive: false,
	},
	{
		name: 'Гимиплегия',
		percent: 20,
		value1: 'G81',
		value2: 'G00-G99',
		image: 'pic/gimiplegia.svg',
		isActive: false,
	},
	{
		name: 'Рак желудка',
		percent: 20,
		value1: 'L53',
		value2: 'A43-Q54',
		image: 'pic/rak_geludka.svg',
		isActive: false,
	},
	{
		name: 'Болезнь паркинсона',
		percent: 20,
		value1: 'T14',
		value2: 'B99-A99',
		image: 'pic/parkinson.svg',
		isActive: true,
	},
]
