export enum AppTypes {
	INITIALIZED_SUCCESS = '@@APP/INITIALIZED_SUCCESS',
	SHOW_MESSAGE = '@@APP/SHOW_MESSAGE',
	DELETE_MESSAGE = '@@APP/DELETE_MESSAGE',
	SET_GLOBAL_LOADER = '@@APP/SET_GLOBAL_LOADER',
	SET_HAVE_USER_DATA = '@@APP/SET_HAVE_USER_DATA',
	SET_STRESS_PARAMS = '@@APP/SET_STRESS_PARAMS',
}
