export enum ChatTypes {
	SEND_MESSAGE = '@@CHAT/SEND_MESSAGE',
	PUT_MESSAGE_TO_STORE = '@@CHAT/PUT_MESSAGE_TO_STORE',
	SET_TYPING = '@@CHAT/SET_TYPING',
	SET_NEW_MESSAGE = '@@CHAT/SET_NEW_MESSAGE',
}
